name: Build iOS Browser

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - uses: actions/checkout@v4

      - name: Build App
        run: |
          xcodebuild \
          -project Telescopure.xcodeproj \
          -scheme Telescopure \
          -sdk iphoneos \
          -configuration Release \
          CODE_SIGNING_ALLOWED=NO \
          archive \
          -archivePath build/Telescopure.xcarchive

      - name: Export IPA
        run: |
          xcodebuild \
          -exportArchive \
          -archivePath build/Telescopure.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath build

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Telescopure-IPA
          path: build/*.ipa
